# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyStartle_gui.ui'
#
# Created: Thu Jan  8 17:33:48 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 752)
        MainWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 35, 1031, 695))
        self.centralwidget.setObjectName("centralwidget")
        self.AcquisitionTabs = QtGui.QTabWidget(self.centralwidget)
        self.AcquisitionTabs.setGeometry(QtCore.QRect(10, 70, 321, 391))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 34, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 34, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 34, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.AcquisitionTabs.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.AcquisitionTabs.setFont(font)
        self.AcquisitionTabs.setTabPosition(QtGui.QTabWidget.North)
        self.AcquisitionTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.AcquisitionTabs.setElideMode(QtCore.Qt.ElideRight)
        self.AcquisitionTabs.setUsesScrollButtons(False)
        self.AcquisitionTabs.setObjectName("AcquisitionTabs")
        self.Stimuli = QtGui.QWidget()
        self.Stimuli.setGeometry(QtCore.QRect(0, 0, 315, 362))
        self.Stimuli.setObjectName("Stimuli")
        self.PP_Stimulus_Enable = QtGui.QGroupBox(self.Stimuli)
        self.PP_Stimulus_Enable.setGeometry(QtCore.QRect(0, 0, 301, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PP_Stimulus_Enable.setPalette(palette)
        font = QtGui.QFont()
        self.PP_Stimulus_Enable.setFont(font)
        self.PP_Stimulus_Enable.setCheckable(False)
        self.PP_Stimulus_Enable.setObjectName("PP_Stimulus_Enable")
        self.layoutWidget = QtGui.QWidget(self.PP_Stimulus_Enable)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 271, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_27 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_5.addWidget(self.label_27)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Condition_Level = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Condition_Level.sizePolicy().hasHeightForWidth())
        self.Condition_Level.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Condition_Level.setFont(font)
        self.Condition_Level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Condition_Level.setDecimals(1)
        self.Condition_Level.setMaximum(120.0)
        self.Condition_Level.setSingleStep(5.0)
        self.Condition_Level.setProperty("value", QtCore.QVariant(40.0))
        self.Condition_Level.setObjectName("Condition_Level")
        self.verticalLayout_3.addWidget(self.Condition_Level)
        self.Condition_Dur = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Condition_Dur.sizePolicy().hasHeightForWidth())
        self.Condition_Dur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Condition_Dur.setFont(font)
        self.Condition_Dur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Condition_Dur.setDecimals(1)
        self.Condition_Dur.setMaximum(10000.0)
        self.Condition_Dur.setSingleStep(5.0)
        self.Condition_Dur.setProperty("value", QtCore.QVariant(1000.0))
        self.Condition_Dur.setObjectName("Condition_Dur")
        self.verticalLayout_3.addWidget(self.Condition_Dur)
        self.Condition_Var = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Condition_Var.sizePolicy().hasHeightForWidth())
        self.Condition_Var.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Condition_Var.setFont(font)
        self.Condition_Var.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Condition_Var.setDecimals(1)
        self.Condition_Var.setMaximum(10000.0)
        self.Condition_Var.setSingleStep(100.0)
        self.Condition_Var.setProperty("value", QtCore.QVariant(1500.0))
        self.Condition_Var.setObjectName("Condition_Var")
        self.verticalLayout_3.addWidget(self.Condition_Var)
        self.PrePulse_Level = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrePulse_Level.sizePolicy().hasHeightForWidth())
        self.PrePulse_Level.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.PrePulse_Level.setFont(font)
        self.PrePulse_Level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_Level.setDecimals(1)
        self.PrePulse_Level.setMaximum(120.0)
        self.PrePulse_Level.setSingleStep(5.0)
        self.PrePulse_Level.setProperty("value", QtCore.QVariant(70.0))
        self.PrePulse_Level.setObjectName("PrePulse_Level")
        self.verticalLayout_3.addWidget(self.PrePulse_Level)
        self.PrePulse_Off_Level = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrePulse_Off_Level.sizePolicy().hasHeightForWidth())
        self.PrePulse_Off_Level.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.PrePulse_Off_Level.setFont(font)
        self.PrePulse_Off_Level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_Off_Level.setDecimals(1)
        self.PrePulse_Off_Level.setMaximum(120.0)
        self.PrePulse_Off_Level.setSingleStep(5.0)
        self.PrePulse_Off_Level.setProperty("value", QtCore.QVariant(0.0))
        self.PrePulse_Off_Level.setObjectName("PrePulse_Off_Level")
        self.verticalLayout_3.addWidget(self.PrePulse_Off_Level)
        self.PrePulse_Dur = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrePulse_Dur.sizePolicy().hasHeightForWidth())
        self.PrePulse_Dur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.PrePulse_Dur.setFont(font)
        self.PrePulse_Dur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_Dur.setDecimals(1)
        self.PrePulse_Dur.setMaximum(5000.0)
        self.PrePulse_Dur.setSingleStep(5.0)
        self.PrePulse_Dur.setProperty("value", QtCore.QVariant(50.0))
        self.PrePulse_Dur.setObjectName("PrePulse_Dur")
        self.verticalLayout_3.addWidget(self.PrePulse_Dur)
        self.Startle_Dur = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Startle_Dur.sizePolicy().hasHeightForWidth())
        self.Startle_Dur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Startle_Dur.setFont(font)
        self.Startle_Dur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Startle_Dur.setDecimals(1)
        self.Startle_Dur.setMaximum(5000.0)
        self.Startle_Dur.setSingleStep(5.0)
        self.Startle_Dur.setProperty("value", QtCore.QVariant(50.0))
        self.Startle_Dur.setObjectName("Startle_Dur")
        self.verticalLayout_3.addWidget(self.Startle_Dur)
        self.Startle_Level = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Startle_Level.sizePolicy().hasHeightForWidth())
        self.Startle_Level.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Startle_Level.setFont(font)
        self.Startle_Level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Startle_Level.setDecimals(0)
        self.Startle_Level.setMinimum(1.0)
        self.Startle_Level.setMaximum(140.0)
        self.Startle_Level.setSingleStep(5.0)
        self.Startle_Level.setProperty("value", QtCore.QVariant(110.0))
        self.Startle_Level.setObjectName("Startle_Level")
        self.verticalLayout_3.addWidget(self.Startle_Level)
        self.PreStartle_Dur = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreStartle_Dur.sizePolicy().hasHeightForWidth())
        self.PreStartle_Dur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.PreStartle_Dur.setFont(font)
        self.PreStartle_Dur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PreStartle_Dur.setDecimals(1)
        self.PreStartle_Dur.setMaximum(5000.0)
        self.PreStartle_Dur.setSingleStep(5.0)
        self.PreStartle_Dur.setProperty("value", QtCore.QVariant(50.0))
        self.PreStartle_Dur.setObjectName("PreStartle_Dur")
        self.verticalLayout_3.addWidget(self.PreStartle_Dur)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.AcquisitionTabs.addTab(self.Stimuli, "")
        self.Wave = QtGui.QWidget()
        self.Wave.setGeometry(QtCore.QRect(0, 0, 315, 362))
        self.Wave.setObjectName("Wave")
        self.ToneTest = QtGui.QPushButton(self.Wave)
        self.ToneTest.setGeometry(QtCore.QRect(40, 310, 101, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.ToneTest.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ToneTest.setFont(font)
        self.ToneTest.setObjectName("ToneTest")
        self.NoiseTest = QtGui.QPushButton(self.Wave)
        self.NoiseTest.setGeometry(QtCore.QRect(160, 310, 111, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.NoiseTest.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NoiseTest.setFont(font)
        self.NoiseTest.setObjectName("NoiseTest")
        self.Waveform_Conditioning = QtGui.QComboBox(self.Wave)
        self.Waveform_Conditioning.setGeometry(QtCore.QRect(10, 30, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Waveform_Conditioning.setFont(font)
        self.Waveform_Conditioning.setObjectName("Waveform_Conditioning")
        self.Waveform_Conditioning.addItem(QtCore.QString())
        self.Waveform_Conditioning.addItem(QtCore.QString())
        self.Waveform_Conditioning.addItem(QtCore.QString())
        self.Waveform_Conditioning.addItem(QtCore.QString())
        self.Waveform_Conditioning.addItem(QtCore.QString())
        self.Waveform_Conditioning.addItem(QtCore.QString())
        self.Waveform_Conditioning.addItem(QtCore.QString())
        self.Waveform_PrePulse = QtGui.QComboBox(self.Wave)
        self.Waveform_PrePulse.setGeometry(QtCore.QRect(130, 30, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Waveform_PrePulse.setFont(font)
        self.Waveform_PrePulse.setObjectName("Waveform_PrePulse")
        self.Waveform_PrePulse.addItem(QtCore.QString())
        self.Waveform_PrePulse.addItem(QtCore.QString())
        self.Waveform_PrePulse.addItem(QtCore.QString())
        self.Waveform_PrePulse.addItem(QtCore.QString())
        self.Waveform_PrePulse.addItem(QtCore.QString())
        self.Waveform_PrePulse.addItem(QtCore.QString())
        self.Waveform_PrePulse.addItem(QtCore.QString())
        self.label_14 = QtGui.QLabel(self.Wave)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.Wave)
        self.label_15.setGeometry(QtCore.QRect(140, 0, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.layoutWidget1 = QtGui.QWidget(self.Wave)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 85, 301, 211))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_24 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_7.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.PrePulse_Freq = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PrePulse_Freq.setFont(font)
        self.PrePulse_Freq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_Freq.setMaximum(100000.0)
        self.PrePulse_Freq.setSingleStep(1000.0)
        self.PrePulse_Freq.setProperty("value", QtCore.QVariant(4000.0))
        self.PrePulse_Freq.setObjectName("PrePulse_Freq")
        self.verticalLayout_6.addWidget(self.PrePulse_Freq)
        self.PrePulse_HP = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PrePulse_HP.setFont(font)
        self.PrePulse_HP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_HP.setMaximum(100000.0)
        self.PrePulse_HP.setSingleStep(1000.0)
        self.PrePulse_HP.setProperty("value", QtCore.QVariant(8000.0))
        self.PrePulse_HP.setObjectName("PrePulse_HP")
        self.verticalLayout_6.addWidget(self.PrePulse_HP)
        self.PrePulse_LP = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PrePulse_LP.setFont(font)
        self.PrePulse_LP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_LP.setMaximum(100000.0)
        self.PrePulse_LP.setSingleStep(1000.0)
        self.PrePulse_LP.setProperty("value", QtCore.QVariant(16000.0))
        self.PrePulse_LP.setObjectName("PrePulse_LP")
        self.verticalLayout_6.addWidget(self.PrePulse_LP)
        self.PrePulse_Notch_F1 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PrePulse_Notch_F1.setFont(font)
        self.PrePulse_Notch_F1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_Notch_F1.setMaximum(100000.0)
        self.PrePulse_Notch_F1.setSingleStep(1000.0)
        self.PrePulse_Notch_F1.setProperty("value", QtCore.QVariant(12000.0))
        self.PrePulse_Notch_F1.setObjectName("PrePulse_Notch_F1")
        self.verticalLayout_6.addWidget(self.PrePulse_Notch_F1)
        self.PrePulse_Notch_F2 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PrePulse_Notch_F2.setFont(font)
        self.PrePulse_Notch_F2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_Notch_F2.setMaximum(100000.0)
        self.PrePulse_Notch_F2.setSingleStep(1000.0)
        self.PrePulse_Notch_F2.setProperty("value", QtCore.QVariant(14000.0))
        self.PrePulse_Notch_F2.setObjectName("PrePulse_Notch_F2")
        self.verticalLayout_6.addWidget(self.PrePulse_Notch_F2)
        self.PrePulse_MultiFreq = QtGui.QLineEdit(self.layoutWidget1)
        self.PrePulse_MultiFreq.setObjectName("PrePulse_MultiFreq")
        self.verticalLayout_6.addWidget(self.PrePulse_MultiFreq)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.PrePulse_GapFlag = QtGui.QCheckBox(self.Wave)
        self.PrePulse_GapFlag.setGeometry(QtCore.QRect(130, 60, 131, 21))
        self.PrePulse_GapFlag.setChecked(True)
        self.PrePulse_GapFlag.setObjectName("PrePulse_GapFlag")
        self.AcquisitionTabs.addTab(self.Wave, "")
        self.Trials = QtGui.QWidget()
        self.Trials.setGeometry(QtCore.QRect(0, 0, 315, 362))
        self.Trials.setObjectName("Trials")
        self.label_17 = QtGui.QLabel(self.Trials)
        self.label_17.setGeometry(QtCore.QRect(90, 10, 131, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.layoutWidget2 = QtGui.QWidget(self.Trials)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 40, 191, 142))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_18 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PrePulse_ITI = QtGui.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrePulse_ITI.sizePolicy().hasHeightForWidth())
        self.PrePulse_ITI.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.PrePulse_ITI.setFont(font)
        self.PrePulse_ITI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_ITI.setDecimals(1)
        self.PrePulse_ITI.setMinimum(0.0)
        self.PrePulse_ITI.setMaximum(600.0)
        self.PrePulse_ITI.setSingleStep(2.0)
        self.PrePulse_ITI.setProperty("value", QtCore.QVariant(20.0))
        self.PrePulse_ITI.setObjectName("PrePulse_ITI")
        self.verticalLayout_2.addWidget(self.PrePulse_ITI)
        self.PrePulse_ITI_Var = QtGui.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrePulse_ITI_Var.sizePolicy().hasHeightForWidth())
        self.PrePulse_ITI_Var.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.PrePulse_ITI_Var.setFont(font)
        self.PrePulse_ITI_Var.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_ITI_Var.setDecimals(1)
        self.PrePulse_ITI_Var.setMinimum(0.0)
        self.PrePulse_ITI_Var.setMaximum(20.0)
        self.PrePulse_ITI_Var.setSingleStep(0.5)
        self.PrePulse_ITI_Var.setProperty("value", QtCore.QVariant(4.0))
        self.PrePulse_ITI_Var.setObjectName("PrePulse_ITI_Var")
        self.verticalLayout_2.addWidget(self.PrePulse_ITI_Var)
        self.PrePulse_Trials = QtGui.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrePulse_Trials.sizePolicy().hasHeightForWidth())
        self.PrePulse_Trials.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.PrePulse_Trials.setFont(font)
        self.PrePulse_Trials.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_Trials.setDecimals(0)
        self.PrePulse_Trials.setMinimum(2.0)
        self.PrePulse_Trials.setMaximum(100.0)
        self.PrePulse_Trials.setProperty("value", QtCore.QVariant(12.0))
        self.PrePulse_Trials.setObjectName("PrePulse_Trials")
        self.verticalLayout_2.addWidget(self.PrePulse_Trials)
        self.PrePulse_NHabTrials = QtGui.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrePulse_NHabTrials.sizePolicy().hasHeightForWidth())
        self.PrePulse_NHabTrials.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.PrePulse_NHabTrials.setFont(font)
        self.PrePulse_NHabTrials.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PrePulse_NHabTrials.setDecimals(0)
        self.PrePulse_NHabTrials.setMinimum(0.0)
        self.PrePulse_NHabTrials.setMaximum(100.0)
        self.PrePulse_NHabTrials.setProperty("value", QtCore.QVariant(2.0))
        self.PrePulse_NHabTrials.setObjectName("PrePulse_NHabTrials")
        self.verticalLayout_2.addWidget(self.PrePulse_NHabTrials)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.AcquisitionTabs.addTab(self.Trials, "")
        self.Analysis = QtGui.QWidget()
        self.Analysis.setGeometry(QtCore.QRect(0, 0, 315, 362))
        self.Analysis.setObjectName("Analysis")
        self.label_19 = QtGui.QLabel(self.Analysis)
        self.label_19.setGeometry(QtCore.QRect(80, 40, 131, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.Analysis_Read = QtGui.QPushButton(self.Analysis)
        self.Analysis_Read.setGeometry(QtCore.QRect(60, 10, 71, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Analysis_Read.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Analysis_Read.setFont(font)
        self.Analysis_Read.setObjectName("Analysis_Read")
        self.Analysis_Analyze = QtGui.QPushButton(self.Analysis)
        self.Analysis_Analyze.setGeometry(QtCore.QRect(140, 10, 61, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Analysis_Analyze.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Analysis_Analyze.setFont(font)
        self.Analysis_Analyze.setObjectName("Analysis_Analyze")
        self.layoutWidget3 = QtGui.QWidget(self.Analysis)
        self.layoutWidget3.setGeometry(QtCore.QRect(22, 70, 241, 142))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_20 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_10.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_10.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_10.addWidget(self.label_23)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Analysis_Start = QtGui.QDoubleSpinBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Analysis_Start.sizePolicy().hasHeightForWidth())
        self.Analysis_Start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Analysis_Start.setFont(font)
        self.Analysis_Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Analysis_Start.setDecimals(1)
        self.Analysis_Start.setMinimum(-250.0)
        self.Analysis_Start.setMaximum(0.0)
        self.Analysis_Start.setSingleStep(25.0)
        self.Analysis_Start.setProperty("value", QtCore.QVariant(-100.0))
        self.Analysis_Start.setObjectName("Analysis_Start")
        self.verticalLayout_9.addWidget(self.Analysis_Start)
        self.Analysis_Duration = QtGui.QDoubleSpinBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Analysis_Duration.sizePolicy().hasHeightForWidth())
        self.Analysis_Duration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Analysis_Duration.setFont(font)
        self.Analysis_Duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Analysis_Duration.setDecimals(1)
        self.Analysis_Duration.setMinimum(20.0)
        self.Analysis_Duration.setMaximum(500.0)
        self.Analysis_Duration.setSingleStep(10.0)
        self.Analysis_Duration.setProperty("value", QtCore.QVariant(100.0))
        self.Analysis_Duration.setObjectName("Analysis_Duration")
        self.verticalLayout_9.addWidget(self.Analysis_Duration)
        self.Analysis_HPF = QtGui.QDoubleSpinBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Analysis_HPF.sizePolicy().hasHeightForWidth())
        self.Analysis_HPF.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Analysis_HPF.setFont(font)
        self.Analysis_HPF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Analysis_HPF.setDecimals(0)
        self.Analysis_HPF.setMinimum(10.0)
        self.Analysis_HPF.setMaximum(5000.0)
        self.Analysis_HPF.setSingleStep(5.0)
        self.Analysis_HPF.setProperty("value", QtCore.QVariant(75.0))
        self.Analysis_HPF.setObjectName("Analysis_HPF")
        self.verticalLayout_9.addWidget(self.Analysis_HPF)
        self.Analysis_LPF = QtGui.QDoubleSpinBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Analysis_LPF.sizePolicy().hasHeightForWidth())
        self.Analysis_LPF.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.Analysis_LPF.setFont(font)
        self.Analysis_LPF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Analysis_LPF.setDecimals(0)
        self.Analysis_LPF.setMinimum(100.0)
        self.Analysis_LPF.setMaximum(10000.0)
        self.Analysis_LPF.setSingleStep(10.0)
        self.Analysis_LPF.setProperty("value", QtCore.QVariant(500.0))
        self.Analysis_LPF.setObjectName("Analysis_LPF")
        self.verticalLayout_9.addWidget(self.Analysis_LPF)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.Analysis_Test = QtGui.QPushButton(self.Analysis)
        self.Analysis_Test.setGeometry(QtCore.QRect(230, 310, 61, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Analysis_Test.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Analysis_Test.setFont(font)
        self.Analysis_Test.setObjectName("Analysis_Test")
        self.AcquisitionTabs.addTab(self.Analysis, "")
        self.Settings = QtGui.QWidget()
        self.Settings.setGeometry(QtCore.QRect(0, 0, 315, 362))
        self.Settings.setObjectName("Settings")
        self.Write_Data = QtGui.QPushButton(self.Settings)
        self.Write_Data.setGeometry(QtCore.QRect(230, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Write_Data.setFont(font)
        self.Write_Data.setObjectName("Write_Data")
        self.Load_Params = QtGui.QPushButton(self.Settings)
        self.Load_Params.setGeometry(QtCore.QRect(30, 180, 111, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Load_Params.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Load_Params.setFont(font)
        self.Load_Params.setObjectName("Load_Params")
        self.Save_Params = QtGui.QPushButton(self.Settings)
        self.Save_Params.setGeometry(QtCore.QRect(170, 180, 111, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Save_Params.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Save_Params.setFont(font)
        self.Save_Params.setObjectName("Save_Params")
        self.layoutWidget4 = QtGui.QWidget(self.Settings)
        self.layoutWidget4.setGeometry(QtCore.QRect(80, 50, 171, 108))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Stimulus_Enable = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Stimulus_Enable.setFont(font)
        self.Stimulus_Enable.setChecked(True)
        self.Stimulus_Enable.setObjectName("Stimulus_Enable")
        self.verticalLayout_4.addWidget(self.Stimulus_Enable)
        self.Waveform_PlotFlag = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Waveform_PlotFlag.setFont(font)
        self.Waveform_PlotFlag.setChecked(True)
        self.Waveform_PlotFlag.setObjectName("Waveform_PlotFlag")
        self.verticalLayout_4.addWidget(self.Waveform_PlotFlag)
        self.OnlineAnalysis_Flag = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.OnlineAnalysis_Flag.setFont(font)
        self.OnlineAnalysis_Flag.setChecked(True)
        self.OnlineAnalysis_Flag.setObjectName("OnlineAnalysis_Flag")
        self.verticalLayout_4.addWidget(self.OnlineAnalysis_Flag)
        self.OnlineSpectrum_Flag = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.OnlineSpectrum_Flag.setFont(font)
        self.OnlineSpectrum_Flag.setChecked(True)
        self.OnlineSpectrum_Flag.setObjectName("OnlineSpectrum_Flag")
        self.verticalLayout_4.addWidget(self.OnlineSpectrum_Flag)
        self.Startle_Debug = QtGui.QCheckBox(self.Settings)
        self.Startle_Debug.setGeometry(QtCore.QRect(30, 250, 101, 21))
        self.Startle_Debug.setObjectName("Startle_Debug")
        self.Hardware_Debug = QtGui.QCheckBox(self.Settings)
        self.Hardware_Debug.setGeometry(QtCore.QRect(170, 250, 121, 21))
        self.Hardware_Debug.setObjectName("Hardware_Debug")
        self.AcquisitionTabs.addTab(self.Settings, "")
        self.QuitButton = QtGui.QPushButton(self.centralwidget)
        self.QuitButton.setGeometry(QtCore.QRect(220, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.QuitButton.setFont(font)
        self.QuitButton.setObjectName("QuitButton")
        self.Status_Window = QtGui.QListWidget(self.centralwidget)
        self.Status_Window.setGeometry(QtCore.QRect(10, 470, 321, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.Status_Window.setFont(font)
        self.Status_Window.setProperty("cursor", QtCore.QVariant(QtCore.Qt.PointingHandCursor))
        self.Status_Window.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Status_Window.setLineWidth(2)
        self.Status_Window.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Status_Window.setAutoScrollMargin(1)
        self.Status_Window.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.Status_Window.setTabKeyNavigation(True)
        self.Status_Window.setProperty("showDropIndicator", QtCore.QVariant(False))
        self.Status_Window.setAlternatingRowColors(False)
        self.Status_Window.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.Status_Window.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.Status_Window.setMovement(QtGui.QListView.Snap)
        self.Status_Window.setProperty("isWrapping", QtCore.QVariant(False))
        self.Status_Window.setLayoutMode(QtGui.QListView.SinglePass)
        self.Status_Window.setSpacing(0)
        self.Status_Window.setUniformItemSizes(False)
        self.Status_Window.setBatchSize(1)
        self.Status_Window.setWordWrap(True)
        self.Status_Window.setObjectName("Status_Window")
        self.PrePulse_Run = QtGui.QPushButton(self.centralwidget)
        self.PrePulse_Run.setGeometry(QtCore.QRect(20, 20, 81, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PrePulse_Run.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.PrePulse_Run.setFont(font)
        self.PrePulse_Run.setObjectName("PrePulse_Run")
        self.PrePulse_Stop = QtGui.QPushButton(self.centralwidget)
        self.PrePulse_Stop.setGeometry(QtCore.QRect(120, 20, 81, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 34, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 34, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 34, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PrePulse_Stop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.PrePulse_Stop.setFont(font)
        self.PrePulse_Stop.setObjectName("PrePulse_Stop")
        self.AutoSave = QtGui.QCheckBox(self.centralwidget)
        self.AutoSave.setGeometry(QtCore.QRect(20, 50, 171, 18))
        self.AutoSave.setChecked(False)
        self.AutoSave.setObjectName("AutoSave")
        self.graphTabs = QtGui.QTabWidget(self.centralwidget)
        self.graphTabs.setGeometry(QtCore.QRect(340, 0, 671, 701))
        self.graphTabs.setObjectName("graphTabs")
        self.graph_StartleTab = QtGui.QWidget()
        self.graph_StartleTab.setGeometry(QtCore.QRect(0, 0, 665, 672))
        self.graph_StartleTab.setObjectName("graph_StartleTab")
        self.qwt_Expanded_Signal_Plot = QwtPlot(self.graph_StartleTab)
        self.qwt_Expanded_Signal_Plot.setGeometry(QtCore.QRect(40, 40, 581, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwt_Expanded_Signal_Plot.sizePolicy().hasHeightForWidth())
        self.qwt_Expanded_Signal_Plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.qwt_Expanded_Signal_Plot.setFont(font)
        self.qwt_Expanded_Signal_Plot.setAutoFillBackground(False)
        self.qwt_Expanded_Signal_Plot.setObjectName("qwt_Expanded_Signal_Plot")
        self.qwt_Discrimination_Plot = QwtPlot(self.graph_StartleTab)
        self.qwt_Discrimination_Plot.setGeometry(QtCore.QRect(130, 340, 421, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwt_Discrimination_Plot.sizePolicy().hasHeightForWidth())
        self.qwt_Discrimination_Plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.qwt_Discrimination_Plot.setFont(font)
        self.qwt_Discrimination_Plot.setAutoFillBackground(False)
        self.qwt_Discrimination_Plot.setObjectName("qwt_Discrimination_Plot")
        self.qwt_Discrimination_Score = QwtTextLabel(self.graph_StartleTab)
        self.qwt_Discrimination_Score.setGeometry(QtCore.QRect(320, 610, 100, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.qwt_Discrimination_Score.setPalette(palette)
        self.qwt_Discrimination_Score.setFrameShape(QtGui.QFrame.Box)
        self.qwt_Discrimination_Score.setFrameShadow(QtGui.QFrame.Raised)
        self.qwt_Discrimination_Score.setObjectName("qwt_Discrimination_Score")
        self.graphTabs.addTab(self.graph_StartleTab, "")
        self.graph_SignalTab = QtGui.QWidget()
        self.graph_SignalTab.setGeometry(QtCore.QRect(0, 0, 665, 672))
        self.graph_SignalTab.setObjectName("graph_SignalTab")
        self.qwt_Response_Plot1 = QwtPlot(self.graph_SignalTab)
        self.qwt_Response_Plot1.setGeometry(QtCore.QRect(20, 10, 631, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwt_Response_Plot1.sizePolicy().hasHeightForWidth())
        self.qwt_Response_Plot1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.qwt_Response_Plot1.setFont(font)
        self.qwt_Response_Plot1.setAutoFillBackground(False)
        self.qwt_Response_Plot1.setObjectName("qwt_Response_Plot1")
        self.qwt_Response_Plot2 = QwtPlot(self.graph_SignalTab)
        self.qwt_Response_Plot2.setGeometry(QtCore.QRect(20, 450, 631, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwt_Response_Plot2.sizePolicy().hasHeightForWidth())
        self.qwt_Response_Plot2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.qwt_Response_Plot2.setFont(font)
        self.qwt_Response_Plot2.setAutoFillBackground(False)
        self.qwt_Response_Plot2.setObjectName("qwt_Response_Plot2")
        self.qwt_RSpectrum_Plot = QwtPlot(self.graph_SignalTab)
        self.qwt_RSpectrum_Plot.setGeometry(QtCore.QRect(20, 230, 301, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwt_RSpectrum_Plot.sizePolicy().hasHeightForWidth())
        self.qwt_RSpectrum_Plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.qwt_RSpectrum_Plot.setFont(font)
        self.qwt_RSpectrum_Plot.setAutoFillBackground(False)
        self.qwt_RSpectrum_Plot.setObjectName("qwt_RSpectrum_Plot")
        self.qwt_LSpectrum_Plot = QwtPlot(self.graph_SignalTab)
        self.qwt_LSpectrum_Plot.setGeometry(QtCore.QRect(350, 230, 301, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwt_LSpectrum_Plot.sizePolicy().hasHeightForWidth())
        self.qwt_LSpectrum_Plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.qwt_LSpectrum_Plot.setFont(font)
        self.qwt_LSpectrum_Plot.setAutoFillBackground(False)
        self.qwt_LSpectrum_Plot.setObjectName("qwt_LSpectrum_Plot")
        self.graphTabs.addTab(self.graph_SignalTab, "")
        self.graph_StimulusTab = QtGui.QWidget()
        self.graph_StimulusTab.setGeometry(QtCore.QRect(0, 0, 665, 672))
        self.graph_StimulusTab.setObjectName("graph_StimulusTab")
        self.qwt_Stimulus_Plot = QwtPlot(self.graph_StimulusTab)
        self.qwt_Stimulus_Plot.setGeometry(QtCore.QRect(10, 30, 621, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwt_Stimulus_Plot.sizePolicy().hasHeightForWidth())
        self.qwt_Stimulus_Plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.qwt_Stimulus_Plot.setFont(font)
        self.qwt_Stimulus_Plot.setAutoFillBackground(False)
        self.qwt_Stimulus_Plot.setObjectName("qwt_Stimulus_Plot")
        self.qwt_Spectrum_Plot = QwtPlot(self.graph_StimulusTab)
        self.qwt_Spectrum_Plot.setGeometry(QtCore.QRect(120, 360, 431, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwt_Spectrum_Plot.sizePolicy().hasHeightForWidth())
        self.qwt_Spectrum_Plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.qwt_Spectrum_Plot.setFont(font)
        self.qwt_Spectrum_Plot.setAutoFillBackground(False)
        self.qwt_Spectrum_Plot.setObjectName("qwt_Spectrum_Plot")
        self.graphTabs.addTab(self.graph_StimulusTab, "")
        self.Rd_Dial = QtGui.QDial(self.centralwidget)
        self.Rd_Dial.setGeometry(QtCore.QRect(300, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Rd_Dial.setFont(font)
        self.Rd_Dial.setAutoFillBackground(False)
        self.Rd_Dial.setMinimum(-150)
        self.Rd_Dial.setMaximum(150)
        self.Rd_Dial.setProperty("value", QtCore.QVariant(2))
        self.Rd_Dial.setSliderPosition(2)
        self.Rd_Dial.setInvertedAppearance(False)
        self.Rd_Dial.setNotchesVisible(True)
        self.Rd_Dial.setObjectName("Rd_Dial")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 640, 120, 51))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.X_Cursor = QtGui.QLabel(self.frame)
        self.X_Cursor.setGeometry(QtCore.QRect(20, 10, 91, 18))
        self.X_Cursor.setFrameShape(QtGui.QFrame.Box)
        self.X_Cursor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.X_Cursor.setObjectName("X_Cursor")
        self.Y_Cursor = QtGui.QLabel(self.frame)
        self.Y_Cursor.setGeometry(QtCore.QRect(20, 30, 91, 18))
        self.Y_Cursor.setFrameShape(QtGui.QFrame.Box)
        self.Y_Cursor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Y_Cursor.setObjectName("Y_Cursor")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 730, 1031, 22))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setGeometry(QtCore.QRect(0, 22, 13, 13))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setGeometry(QtCore.QRect(13, 22, 13, 13))
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtGui.QToolBar(MainWindow)
        self.toolBar_3.setGeometry(QtCore.QRect(26, 22, 13, 13))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.toolBar_3.setPalette(palette)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.toolBar_4 = QtGui.QToolBar(MainWindow)
        self.toolBar_4.setGeometry(QtCore.QRect(39, 22, 992, 13))
        self.toolBar_4.setObjectName("toolBar_4")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_4)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen_2 = QtGui.QAction(MainWindow)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionParameters = QtGui.QAction(MainWindow)
        self.actionParameters.setObjectName("actionParameters")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuDatabase.addAction(self.actionNew)
        self.menuDatabase.addAction(self.actionOpen_2)
        self.menuDatabase.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionParameters)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.AcquisitionTabs.setCurrentIndex(0)
        self.Waveform_Conditioning.setCurrentIndex(0)
        self.Waveform_PrePulse.setCurrentIndex(0)
        self.graphTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyStartle", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_Stimulus_Enable.setTitle(QtGui.QApplication.translate("MainWindow", "Startle Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Conditioning (dB SPL)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Conditioning Dur (msec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Conditioning Var (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Prepulse ON (dB SPL)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Prepulse OFF (dB SPL)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Prepulse Dur (msec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "PreStartle (msec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Startle (dB SPL)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Startle (msec)", None, QtGui.QApplication.UnicodeUTF8))
        self.AcquisitionTabs.setTabText(self.AcquisitionTabs.indexOf(self.Stimuli), QtGui.QApplication.translate("MainWindow", "Stimuli", None, QtGui.QApplication.UnicodeUTF8))
        self.ToneTest.setText(QtGui.QApplication.translate("MainWindow", "Tone Test", None, QtGui.QApplication.UnicodeUTF8))
        self.NoiseTest.setText(QtGui.QApplication.translate("MainWindow", "Noise Test", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_Conditioning.setItemText(0, QtGui.QApplication.translate("MainWindow", "Silence", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_Conditioning.setItemText(1, QtGui.QApplication.translate("MainWindow", "Tone", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_Conditioning.setItemText(2, QtGui.QApplication.translate("MainWindow", "BP Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_Conditioning.setItemText(3, QtGui.QApplication.translate("MainWindow", "Notch Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_Conditioning.setItemText(4, QtGui.QApplication.translate("MainWindow", "MultiTones", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_Conditioning.setItemText(5, QtGui.QApplication.translate("MainWindow", "AM Tones", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_Conditioning.setItemText(6, QtGui.QApplication.translate("MainWindow", "AM Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_PrePulse.setItemText(0, QtGui.QApplication.translate("MainWindow", "Silence", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_PrePulse.setItemText(1, QtGui.QApplication.translate("MainWindow", "Tone", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_PrePulse.setItemText(2, QtGui.QApplication.translate("MainWindow", "BP Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_PrePulse.setItemText(3, QtGui.QApplication.translate("MainWindow", "Notch Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_PrePulse.setItemText(4, QtGui.QApplication.translate("MainWindow", "MultiTones", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_PrePulse.setItemText(5, QtGui.QApplication.translate("MainWindow", "AM Tone", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_PrePulse.setItemText(6, QtGui.QApplication.translate("MainWindow", "AM Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Conditioning Stimulus Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "PrePulse Stimulus Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Tone Freq (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Noise HP (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Noise LP (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Notch F1 (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Notch F2 (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Multitone (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.PrePulse_MultiFreq.setText(QtGui.QApplication.translate("MainWindow", "linspace(2.0,32.0,4.0)", None, QtGui.QApplication.UnicodeUTF8))
        self.PrePulse_GapFlag.setText(QtGui.QApplication.translate("MainWindow", "PrePulse in Gap?", None, QtGui.QApplication.UnicodeUTF8))
        self.AcquisitionTabs.setTabText(self.AcquisitionTabs.indexOf(self.Wave), QtGui.QApplication.translate("MainWindow", "Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Trial Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "ITI (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "ITI Var (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Trials", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Habituation Trials", None, QtGui.QApplication.UnicodeUTF8))
        self.AcquisitionTabs.setTabText(self.AcquisitionTabs.indexOf(self.Trials), QtGui.QApplication.translate("MainWindow", "Trials", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Analysis Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.Analysis_Read.setText(QtGui.QApplication.translate("MainWindow", "Read File", None, QtGui.QApplication.UnicodeUTF8))
        self.Analysis_Analyze.setText(QtGui.QApplication.translate("MainWindow", "Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Window Start \n"
" re Startle (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Window Post \n"
"Startle (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "HPF (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "LPF (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.Analysis_Test.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.AcquisitionTabs.setTabText(self.AcquisitionTabs.indexOf(self.Analysis), QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.Write_Data.setText(QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.Load_Params.setText(QtGui.QApplication.translate("MainWindow", "Load Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.Save_Params.setText(QtGui.QApplication.translate("MainWindow", "Save Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_Enable.setText(QtGui.QApplication.translate("MainWindow", "Enable Stimulus", None, QtGui.QApplication.UnicodeUTF8))
        self.Waveform_PlotFlag.setText(QtGui.QApplication.translate("MainWindow", "Plot Waveform", None, QtGui.QApplication.UnicodeUTF8))
        self.OnlineAnalysis_Flag.setText(QtGui.QApplication.translate("MainWindow", "Online Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.OnlineSpectrum_Flag.setText(QtGui.QApplication.translate("MainWindow", "Spectrum Compute", None, QtGui.QApplication.UnicodeUTF8))
        self.Startle_Debug.setText(QtGui.QApplication.translate("MainWindow", "Startle Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.Hardware_Debug.setText(QtGui.QApplication.translate("MainWindow", "Hardware Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.AcquisitionTabs.setTabText(self.AcquisitionTabs.indexOf(self.Settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.QuitButton.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.Status_Window.setToolTip(QtGui.QApplication.translate("MainWindow", "Click to select data to load and display", None, QtGui.QApplication.UnicodeUTF8))
        self.PrePulse_Run.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.PrePulse_Stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.AutoSave.setText(QtGui.QApplication.translate("MainWindow", "Automatically Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.graph_StartleTab), QtGui.QApplication.translate("MainWindow", "Startle/Discrim", None, QtGui.QApplication.UnicodeUTF8))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.graph_SignalTab), QtGui.QApplication.translate("MainWindow", "Signals", None, QtGui.QApplication.UnicodeUTF8))
        self.graphTabs.setTabText(self.graphTabs.indexOf(self.graph_StimulusTab), QtGui.QApplication.translate("MainWindow", "Stimulus", None, QtGui.QApplication.UnicodeUTF8))
        self.X_Cursor.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Y_Cursor.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setTitle(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_3.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_3", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_4.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_2.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParameters.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4.Qwt5 import QwtTextLabel, QwtPlot
